### ISSUE TITLE
Milestones: Cosmos Governance Briefings

### ISSUE THREAD

**Issue by Philipp-Sc** [Philipp-Sc/terra-rust-bot#4]
- [ ]  Show (Validator) Votes 
- [ ]  Show Deposited Amount
- [ ]  **Migrate Subscription Functionality to Web-UI (!)**
 - Settings to hide spam/fraud based on Fraud Likelihood + In Deposit Period + NoWithVeto Percentage
- [ ] **Daily or weekly briefing/bulletin for that store timeline of notifications (for the user and their subscriptions) (!)**
- -  [ ] Allows the user to request their timeline.
- -  [ ] Allows the user to set subscriptions to silent. (to view notifications the user needs to request timeline)
- [ ]  Enable Translation

**Comment by Philipp-Sc** [comment]
- [ ] **Daily or weekly briefing/bulletin for that store timeline of notifications (for the user and their subscriptions) (!)**
- -  [ ] Advanced features (Summarize/Generate Briefing) using the timeline
- [ ] Present AI generated content via synthetic voice. Integrate with YT.

- [ ]  Add DAOs 
https://github.com/DA0-DA0/dao-contracts
https://github.com/terra-money/enterprise-contracts
- [ ]  https://github.com/Philipp-Sc/rust-bert-fraud-detection/issues/1#issue-1666625726
 (including DAO governance proposals)

**Comment by Philipp-Sc** [comment]
- [ ]  Refactor Signal Bot 
- [ ]  Similar Proposals
- [ ]  Search Proposals
- [ ]  Explain/Talk to/Question Proposal (Chat with a ChatGPT about the proposal)
- [ ]  Watch out for specific topics/proposal types
- [ ] Rank proposals by importance (using AI)
